name = "ai-link-in-bio-editor"
compatibility_date = "2025-08-21"
main = "src/worker.js"

# Assets configuration for React SPA
[assets]
directory = "./dist"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "link-in-bio-db"
database_id = "placeholder-database-id"
preview_database_id = "placeholder-preview-database-id"
migrations_dir = "migrations"

# R2 Bucket binding for image storage
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "link-in-bio-images"
preview_bucket_name = "link-in-bio-images-preview"

[vars]
# Environment variables for your Gemini API key
# Use wrangler secret to set sensitive values:
# wrangler secret put GEMINI_API_KEY
