name = "ai-link-in-bio-editor-worker"
compatibility_date = "2024-01-01"
account_id = "***ACCOUNT_ID_REMOVED***"

# Assets configuration for React SPA
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
NODE_ENV = "production"

# Environment variables for your Gemini API key
# Use wrangler secret to set sensitive values:
# wrangler secret put GEMINI_API_KEY