name = "ai-link-in-bio-editor"
compatibility_date = "2025-08-21"
main = "src/worker.js"

# Assets configuration for React SPA  
# Note: Deploy to Cloudflare may not support [assets] properly
# Assets will be handled by the worker fallback mechanism
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "link-in-bio-db"
database_id = "placeholder-database-id"
preview_database_id = "placeholder-preview-database-id"
migrations_dir = "migrations"

# R2 Bucket binding for image storage
# For faster image loading, enable public access on your R2 bucket:
# 1. Cloudflare Dashboard → R2 Object Storage → link-in-bio-images → Settings
# 2. Enable "Public URL Access" to use https://link-in-bio-images.r2.dev/ URLs
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "link-in-bio-images"
preview_bucket_name = "link-in-bio-images-preview"

[vars]
# For production, set a custom domain for R2 images (optional but recommended):
# R2_PUBLIC_URL = "https://images.yourdomain.com"

# Environment variables for your Gemini API key
# Use wrangler secret to set sensitive values:
# wrangler secret put GEMINI_API_KEY
