name = "ai-link-in-bio-editor"
compatibility_date = "2025-08-21"
main = "worker-wrapper.js"

# Configure for ES Module format
[build]
command = "npm run build"

# Assets configuration for React Router v7
[assets]
directory = "./build/client"
not_found_handling = "single-page-application"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "link-in-bio-db"
database_id = "e23c7652-ee14-49d0-84a7-34c34212ebc6"
preview_database_id = "e23c7652-ee14-49d0-84a7-34c34212ebc6"
migrations_dir = "migrations"

# R2 Bucket binding for image storage
# Images are served through Worker API by default (/api/image/filename)
# This provides good performance with proper caching and CORS headers
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "link-in-bio-images"
preview_bucket_name = "link-in-bio-images-preview"

[vars]
# Optional: For maximum performance, set up a custom domain for R2 images
# 1. Configure custom domain in Cloudflare Dashboard → R2 → Your Bucket → Settings
# 2. Set the custom domain URL below:
# R2_PUBLIC_URL = "https://images.yourdomain.com"

# Environment variables for your Gemini API key
# Use wrangler secret to set sensitive values:
# wrangler secret put GEMINI_API_KEY

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
