name = "ai-link-in-bio-editor"
compatibility_date = "2025-08-21"
main = "worker-wrapper.js"

# Configure for ES Module format
[build]
command = "npm run build"

# Assets configuration for React Router v7
[assets]
directory = "./build/client"
not_found_handling = "single-page-application"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "link-in-bio-db"
database_id = "e23c7652-ee14-49d0-84a7-34c34212ebc6"
preview_database_id = "e23c7652-ee14-49d0-84a7-34c34212ebc6"
migrations_dir = "migrations"

# R2 Bucket binding for image storage
# Images are served through Worker API by default (/api/image/filename)
# This provides good performance with proper caching and CORS headers
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "link-in-bio-images"
preview_bucket_name = "link-in-bio-images-preview"

[vars]
# R2 Public URL for direct image access (optional - improves performance)
# Leave empty to use worker proxy, or set to your R2 public URL for direct access
# To enable: run `wrangler r2 bucket dev-url enable YOUR_BUCKET_NAME`
# R2_PUBLIC_URL = "https://pub-xxxxxxxxxx.r2.dev"

# Environment variables for your Gemini API key
# Use wrangler secret to set sensitive values:
# wrangler secret put GEMINI_API_KEY

# Observability and monitoring
[observability.logs]
enabled = true

# Security headers for web application
[assets.headers."*"]
"X-Content-Type-Options" = "nosniff"
"X-Frame-Options" = "DENY" 
"X-XSS-Protection" = "1; mode=block"
"Referrer-Policy" = "strict-origin-when-cross-origin"
