// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/preview": {
    params: {};
  };
  "/api/data": {
    params: {};
  };
  "/api/save": {
    params: {};
  };
  "/api/upload-image": {
    params: {};
  };
  "/api/image/:filename": {
    params: {
      "filename": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/about" | "/preview" | "/api/data" | "/api/save" | "/api/upload-image" | "/api/image/:filename";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/preview.tsx": {
    id: "routes/preview";
    page: "/preview";
  };
  "routes/api.data.tsx": {
    id: "routes/api.data";
    page: "/api/data";
  };
  "routes/api.save.tsx": {
    id: "routes/api.save";
    page: "/api/save";
  };
  "routes/api.upload-image.tsx": {
    id: "routes/api.upload-image";
    page: "/api/upload-image";
  };
  "routes/api.image.$filename.tsx": {
    id: "routes/api.image.$filename";
    page: "/api/image/:filename";
  };
};